[theme]
base="dark"
primaryColor="#2a9d8f"
backgroundColor="#08131f"
secondaryBackgroundColor="#10202f"
textColor="#edf6f9"
font="sans serif"
baseRadius="large"
borderColor="#213547"
showWidgetBorder=true
